:r .\Populate\Populate_PresentationType.sql
:r .\Populate\Populate_Presentation.sql
:r .\Populate\Populate_Tag.sql
:r .\Populate\Populate_PresentationTag.sql
:r .\Populate\Populate_PresentationRelated.sql
:r .\Populate\Populate_LearningObjective.sql
:r .\Populate\Populate_ShindigStatus.sql
:r .\Populate\Populate_ShindigType.sql
:r .\Populate\Populate_Shindig.sql
:r .\Populate\Populate_ShindigPresentation.sql
:r .\Populate\Populate_ShindigPresentationDownload.sql
:r .\Populate\Populate_CommitType.sql
:r .\Populate\Populate_TemplateType.sql
:r .\Populate\Populate_Template.sql